// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD53qYnL_yYtFkVbzy7fV3uzcNca9oF8LA',
    appId: '1:1065490803245:web:95c7728e99eb46cd7ee6a4',
    messagingSenderId: '1065490803245',
    projectId: 'healysis',
    authDomain: 'healysis.firebaseapp.com',
    storageBucket: 'healysis.appspot.com',
    measurementId: 'G-6HSL10RKTZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVYdDnxof6QlhDIkuiYkmqBYYe2LAQit8',
    appId: '1:1065490803245:android:d078782708b2044c7ee6a4',
    messagingSenderId: '1065490803245',
    projectId: 'healysis',
    storageBucket: 'healysis.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaC7BAh5pkGaJDiMX1FDZ1-BtIiTlZFOI',
    appId: '1:1065490803245:ios:02d5f472cd0033407ee6a4',
    messagingSenderId: '1065490803245',
    projectId: 'healysis',
    storageBucket: 'healysis.appspot.com',
    iosClientId: '1065490803245-8ghb94d4a199jdse3pv314ht4tnn6rgo.apps.googleusercontent.com',
    iosBundleId: 'com.example.webApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaC7BAh5pkGaJDiMX1FDZ1-BtIiTlZFOI',
    appId: '1:1065490803245:ios:02d5f472cd0033407ee6a4',
    messagingSenderId: '1065490803245',
    projectId: 'healysis',
    storageBucket: 'healysis.appspot.com',
    iosClientId: '1065490803245-8ghb94d4a199jdse3pv314ht4tnn6rgo.apps.googleusercontent.com',
    iosBundleId: 'com.example.webApp',
  );
}
